### ISSUE TITLE
Failed to build with Qt 5.11.2

### ISSUE THREAD

**Issue by arietto** [Skycoder42/QJsonSerializer#16]
Hello!  I can't build your library using Qt 5.11.2 in Windows (MS VS 2017). But Qt 5.12.1 works fine. At least, please, add minimal supported Qt version.

Creating library ..\..\lib\Qt5JsonSerializerd.lib and object ..\..\lib\Qt5JsonSerializerd.exp
qjsonconverterreg_22.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) unsigned int __cdecl qHash(class QJsonValue const &,unsigned int)" (__imp_?qHash@@YAIAEBVQJsonValue@@I@Z) referenced in function "private: struct QHashNode<class QJsonValue,struct QHashDummyValue> * * __cdecl QHash<class QJsonValue,struct QHashDummyValue>::findNode(class QJsonValue const &,unsigned int *)const " (?findNode@?$QHash@VQJsonValue@@UQHashDummyValue@@@@AEBAPEAPEAU?$QHashNode@VQJsonValue@@UQHashDummyValue@@@@AEBVQJsonValue@@PEAI@Z)
qjsonconverterreg_23.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) unsigned int __cdecl qHash(class QJsonObject const &,unsigned int)" (__imp_?qHash@@YAIAEBVQJsonObject@@I@Z) referenced in function "private: struct QHashNode<class QJsonObject,struct QHashDummyValue> * * __cdecl QHash<class QJsonObject,struct QHashDummyValue>::findNode(class QJsonObject const &,unsigned int *)const " (?findNode@?$QHash@VQJsonObject@@UQHashDummyValue@@@@AEBAPEAPEAU?$QHashNode@VQJsonObject@@UQHashDummyValue@@@@AEBVQJsonObject@@PEAI@Z)
qjsonconverterreg_24.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) unsigned int __cdecl qHash(class QJsonArray const &,unsigned int)" (__imp_?qHash@@YAIAEBVQJsonArray@@I@Z) referenced in function "private: struct QHashNode<class QJsonArray,struct QHashDummyValue> * * __cdecl QHash<class QJsonArray,struct QHashDummyValue>::findNode(class QJsonArray const &,unsigned int *)const " (?findNode@?$QHash@VQJsonArray@@UQHashDummyValue@@@@AEBAPEAPEAU?$QHashNode@VQJsonArray@@UQHashDummyValue@@@@AEBVQJsonArray@@PEAI@Z)
..\..\lib\Qt5JsonSerializerd.dll : fatal error LNK1120: 3 unresolved externals
NMAKE : fatal error U1077: '"D:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\link.EXE"' : return code '0x460'
Stop.

**Comment by Skycoder42** [comment]
Generelly speaking, I always only support the latest version of Qt, as I do not want to limit myself for the sake of backwards compability. Also, doing so often makes code messy over time and requires testing for all the different supported versions.

You can use the releases page to check which is the latest one that was build for the Qt version you try to target. For example, `3.2.0` is the latest tag that was build against 5.11. Typically I add a note to a release when I switch to a newer version of Qt.

That beeing said, as long as the difference is not to big, I always accept pull requests trying to add compability to an older version.

For your concrete problem, there seems to be no method to generate a hash for the json classes, wich is needed by QSet/QHash. A workaround could be to remove `QJsonValue QJsonObject QJsonArray` from `ALL_TYPES` and add them to `LIST_TYPES` (and `MAP_TYPES`) in [typesplit.pri](https://github.com/Skycoder42/QtJsonSerializer/blob/master/src/jsonserializer/typesplit.pri). If that works for you, feel free to create a pull request that does so conditionally based on the Qt-Version that is beeing used.

**Comment by arietto** [comment]
OK, thanks.
