### ISSUE TITLE
build with Qt5.10.1 on windows and macos got errors

### ISSUE THREAD

**Issue by toby20130333** [Skycoder42/QJsonSerializer#21]
Hi all
 I build this source code on windows and macos with Qt5.10.1.but I got some errors
```
/Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers/qhashfunctions.h:112:35: error: no matching function for call to 'qHash'
    Q_DECL_NOEXCEPT_EXPR(noexcept(qHash(t)))

 FullValidation = (NoExtraProperties | AllProperties)
//        FullValidation Q_DECL_ENUMERATOR_DEPRECATED_X("Use QJsonSerializer::FullValidation2 or QJsonSerializer::FullPropertyValidation instead") = (NoExtraProperties | AllProperties)
```
and source code 

```
#if !defined(QT_NO_EXCEPTIONS) //&& QT_CONFIG(future)
#include <QtCore/qexception.h>
#define QT_JSONSERIALIZER_EXCEPTION_BASE QException
#define QT_JSONSERIALIZER_EXCEPTION_OR override
#else
#include <exception>
#define QT_JSONSERIALIZER_EXCEPTION_BASE std::exception
#define QT_JSONSERIALIZER_EXCEPTION_OR
#endif
```
what's wrong with my platform or build tools?

**Comment by Skycoder42** [comment]
The latest version of this library requires Qt 5.13. For older versions of Qt, please use the last version of this library that was published for that respective version. As seen on the releases page, [Version 3.1.2](https://github.com/Skycoder42/QtJsonSerializer/releases/tag/3.1.2) is the last version for Qt 5.10.

**Comment by toby20130333** [comment]
ok thanks




| |
tb1210582007
邮箱：tb1210582007@126.com
|

Signature is customized by Netease Mail Master

On 08/17/2019 17:57, Felix Barz wrote:

The latest version of this library requires Qt 5.13. For older versions of Qt, please use the last version of this library that was published for that respective version. As seen on the releases page, (Version 3.1.2)[https://github.com/Skycoder42/QtJsonSerializer/releases/tag/3.1.2] is the last version for Qt 5.10.
